name: Multi Step
on:
  workflow_dispatch:
    inputs:
        environment:
          type: environment
          description: Choose the env to land
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Py
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Run Py
        run: |
          python main.py
  dev:
    name: Deploy to DEV
    if: github.event_name=='push'
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: Dev
    steps:
        - name: Deploying
          run: echo Deploying to DEV
  test:
    name: Deploy to TEST
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: Test
    steps:
        - name: Deploying
          run: echo Deploying to TEST

  stage:
    name: Deploy to STAGE
    runs-on: ubuntu-latest
    needs: [build]
    environment: 
      name: Stage
    steps:
        - name: Deploying
          run: echo Deploying to STAGE

  prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: [stage]
    environment: 
      name: Prod
    steps:
        - name: Deploying
          run: echo Deploying to PROD
